"use strict";
const $=id=>document.getElementById(id);
const els={app:$('app'),home:$('homeScreen'),quiz:$('quizScreen'),result:$('resultScreen'),error:$('errorScreen'),errorMessage:$('errorMessage'),start:$('startButton'),progress:$('progressText'),category:$('categoryText'),timer:$('timerNumber'),timerRing:$('timerRing'),question:$('questionText'),answers:$('answerList'),feedback:$('feedback'),feedbackTitle:$('feedbackTitle'),feedbackFact:$('feedbackFact'),score:$('scoreText'),classification:$('classificationText'),resultMessage:$('resultMessage'),correct:$('correctStat'),incorrect:$('incorrectStat'),unanswered:$('unansweredStat'),average:$('averageStat'),discoverTitle:$('discoverTitle'),platformLinks:$('platformLinks'),replay:$('replayButton'),share:$('shareButton'),copy:$('copyButton'),shareStatus:$('shareStatus'),homeBandName:$('homeBandName'),edition:$('editionName'),quizTitle:$('quizTitle')};
const VERSION='20260713-4';
let config,questionBank=[],freshQuestionBank=null,questions=[],index=0,answers=[],locked=false,timerInterval=null,timerDeadline=0,advanceTimeout=null,muted=readMutePreference();
let ding=null;
const analytics={track(event,data={}){window.dispatchEvent(new CustomEvent('fan-challenge-analytics',{detail:{event,...data}}))}};

init();
async function init(){try{config=await fetchJson(`config/band.json?v=${VERSION}`);questionBank=await fetchJson(`${config.questionFile}?v=${VERSION}`);validateRuntimeContent();freshQuestionBank=new SevenSecondsBandEngine.FreshQuestionBank(questionBank,config.questionMix);applyConfig();createAudio();syncMuteControls();els.start.disabled=false}catch(error){console.error(error);showError('The challenge content could not be loaded. Please refresh and try again.')}}
async function fetchJson(url){const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error(`${url} returned ${response.status}`);return response.json()}
function validateRuntimeContent(){const active=questionBank.filter(q=>q.active);if(active.length<config.numberOfQuestions)throw new Error('Not enough active questions');for(const q of active){if(!q.id||!q.question||!Array.isArray(q.options)||q.options.length!==4||!q.options.includes(q.correctAnswer))throw new Error(`Invalid question ${q.id||'unknown'}`)}}
function applyConfig(){document.title=`${config.brandName} – ${config.editionTitle}`;els.homeBandName.textContent=config.bandName;els.discoverTitle.textContent=`Discover ${config.bandName}`;document.documentElement.style.setProperty('--accent',config.theme.accent);document.documentElement.style.setProperty('--accent2',config.theme.accentSecondary);document.documentElement.style.setProperty('--brand-art',`url("${config.brandArtwork}")`);document.documentElement.style.setProperty('--background-art',`url("${config.backgroundArtwork}")`);buildPlatformLinks()}
function createAudio(){ding=new Audio(`${config.dingSound}?v=${VERSION}`);ding.preload='auto';ding.playsInline=true;ding.load()}
function unlockAudio(){if(!ding||muted)return;ding.muted=true;ding.currentTime=0;const attempt=ding.play();if(attempt&&attempt.then)attempt.then(()=>{ding.pause();ding.currentTime=0;ding.muted=false}).catch(()=>{ding.muted=false})}
function playDing(){if(!ding||muted)return;try{ding.pause();ding.currentTime=0;ding.muted=false;const attempt=ding.play();if(attempt&&attempt.catch)attempt.catch(error=>console.warn('Ding blocked:',error))}catch(error){console.warn('Ding unavailable:',error)}}
function startChallenge(){unlockAudio();analytics.track('challenge_started',{band:config.bandName});startRun()}
function startRun(){clearTimers();questions=freshQuestionBank.nextRound();index=0;answers=[];showScreen(els.quiz);renderQuestion()}
function renderQuestion(){clearTimers();locked=false;els.feedback.hidden=true;els.answers.innerHTML='';const q=questions[index];els.progress.textContent=`Question ${index+1} of ${questions.length}`;els.category.textContent=q.category;els.question.textContent=q.question;els.timer.textContent=String(config.secondsPerQuestion);els.timerRing.classList.remove('urgent');els.timerRing.setAttribute('aria-label',`${config.secondsPerQuestion} seconds remaining`);q.options.forEach((option,optionIndex)=>{const button=document.createElement('button');button.type='button';button.className='answer-button';button.textContent=`${String.fromCharCode(65+optionIndex)}. ${option}`;button.dataset.answer=option;button.addEventListener('click',()=>selectAnswer(option,button));els.answers.append(button)});els.question.focus({preventScroll:true});timerDeadline=performance.now()+config.secondsPerQuestion*1000;timerInterval=setInterval(updateTimer,50)}
function updateTimer(){if(locked)return;const remainingMs=timerDeadline-performance.now();const remaining=Math.max(0,Math.ceil(remainingMs/1000));els.timer.textContent=String(remaining);els.timerRing.setAttribute('aria-label',`${remaining} seconds remaining`);els.timerRing.classList.toggle('urgent',remaining<=2&&remaining>0);if(remainingMs<=0)completeAnswer(null,true)}
function selectAnswer(answer,button){if(locked)return;button.classList.add(answer===questions[index].correctAnswer?'correct':'incorrect');completeAnswer(answer,false)}
function completeAnswer(selected,unanswered){if(locked)return;locked=true;clearInterval(timerInterval);timerInterval=null;const q=questions[index];const correct=!unanswered&&selected===q.correctAnswer;const responseSeconds=unanswered?config.secondsPerQuestion:Math.min(config.secondsPerQuestion,Math.max(0,(config.secondsPerQuestion*1000-(timerDeadline-performance.now()))/1000));answers.push({id:q.id,selected,correct,unanswered,responseSeconds});for(const button of els.answers.children){button.disabled=true;if(button.dataset.answer===q.correctAnswer)button.classList.add('correct')}
  els.timer.textContent=unanswered?'0':els.timer.textContent;els.timerRing.classList.remove('urgent');els.feedbackTitle.textContent=unanswered?`TIME’S UP — ${q.correctAnswer}`:correct?'CORRECT':`NOT QUITE — ${q.correctAnswer}`;els.feedbackFact.textContent=q.explanation;els.feedback.hidden=false;if(correct)playDing();analytics.track('question_answered',{questionId:q.id,correct,unanswered,responseSeconds});advanceTimeout=setTimeout(()=>{index+=1;if(index>=questions.length)showResults();else renderQuestion()},config.feedbackMilliseconds)}
function showResults(){clearTimers();const stats=SevenSecondsBandEngine.calculateStats(answers,questions.length);const result=SevenSecondsBandEngine.classificationFor(stats.correct,config.classifications,config.bandName);els.score.textContent=`${stats.correct} / ${questions.length}`;els.classification.textContent=result.label;els.resultMessage.textContent=result.message;els.correct.textContent=stats.correct;els.incorrect.textContent=stats.incorrect;els.unanswered.textContent=stats.unanswered;els.average.textContent=`${stats.averageResponseTime.toFixed(1)}s`;els.result.dataset.score=String(stats.correct);els.result.dataset.classification=result.label;showScreen(els.result);analytics.track('challenge_completed',{score:stats.correct,classification:result.label})}
function showScreen(screen){[els.home,els.quiz,els.result,els.error].forEach(item=>item.hidden=item!==screen);els.app.classList.toggle('home-active',screen===els.home);window.scrollTo({top:0,behavior:'auto'})}
function showError(message){clearTimers();els.errorMessage.textContent=message;showScreen(els.error)}
function clearTimers(){if(timerInterval){clearInterval(timerInterval);timerInterval=null}if(advanceTimeout){clearTimeout(advanceTimeout);advanceTimeout=null}}
function buildPlatformLinks(){const definitions=[['spotify','Open Spotify','spotify'],['bandcamp','Visit Bandcamp','bandcamp'],['youtube','Watch YouTube','youtube'],['instagram','Open Instagram','instagram'],['website','Visit Website','website'],['tickets','Buy Tickets','tickets'],['merchandise','Buy Merch','merchandise'],['mailingList','Join Mailing List','mailing-list']];els.platformLinks.innerHTML='';definitions.forEach(([key,label,className])=>{const url=config.links[key];if(!url)return;const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener noreferrer';link.className=`platform-link ${className}`;link.textContent=label;link.setAttribute('aria-label',`${label} for ${config.bandName} (opens in a new tab)`);link.addEventListener('click',()=>analytics.track('platform_clicked',{platform:key,band:config.bandName}));els.platformLinks.append(link)})}
function resultShareText(){return `I scored ${els.result.dataset.score}/${questions.length} in the ${config.bandName} Fan Challenge and earned ${els.result.dataset.classification} status. Can you beat me?`}
async function shareResult(){const payload={title:`${config.brandName} – ${config.editionTitle}`,text:resultShareText(),url:location.href};if(navigator.share){try{await navigator.share(payload);analytics.track('result_shared');return}catch(error){if(error.name==='AbortError')return}}await copyText(`${payload.text}\n${payload.url}`,'Challenge copied to your clipboard.')}
async function copyQuizLink(){await copyText(location.href,'Quiz link copied.')}
async function copyText(text,success){try{await navigator.clipboard.writeText(text);els.shareStatus.textContent=success}catch(error){els.shareStatus.textContent='Copy was blocked. Please copy the address from your browser.'}}
function readMutePreference(){try{return localStorage.getItem('fanChallengeMuted')==='true'}catch{return false}}
function setMuted(value){muted=value;try{localStorage.setItem('fanChallengeMuted',String(value))}catch{}syncMuteControls();analytics.track('sound_changed',{muted})}
function syncMuteControls(){document.querySelectorAll('.mute-button').forEach(button=>{button.setAttribute('aria-pressed',String(muted));button.setAttribute('aria-label',muted?'Turn sound on':'Mute sound');button.textContent=button.id==='muteButtonHome'?`Sound: ${muted?'Off':'On'}`:(muted?'×':'♪')})}
function toggleMute(){setMuted(!muted)}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&timerInterval&&!locked)updateTimer()});
window.addEventListener('beforeunload',clearTimers);
els.start.addEventListener('click',startChallenge);els.replay.addEventListener('click',()=>{unlockAudio();analytics.track('challenge_replayed');startRun()});els.share.addEventListener('click',shareResult);els.copy.addEventListener('click',copyQuizLink);document.querySelectorAll('.mute-button').forEach(button=>button.addEventListener('click',toggleMute));
window.__bandChallengeTest={startRun,renderQuestion,completeAnswer,showResults,getState:()=>({index,locked,answerCount:answers.length,timerValue:els.timer.textContent,screen:els.home.hidden?(els.quiz.hidden?'result':'quiz'):'home',questions:questions.map(q=>q.id)})};
